name: ${rootProject.name}
version: ${version}
main: fr.just2craft.customcraft.CustomCraft
author: fabien91
website: ${website}
api-version: 1.13

commands:
  customcraft:
    usage: /customcraft
    description: Base command